export const TokenType = {
  TAG_OPEN_START: 'TAG_OPEN_START',
  TAG_OPEN_END: 'TAG_OPEN_END',
  TAG_OPEN_END_VOID: 'TAG_OPEN_END_VOID',
  TAG_CLOSE: 'TAG_CLOSE',
  INCOMPLETE_TAG_OPEN: 'INCOMPLETE_TAG_OPEN',
  TEXT: 'TEXT',
  ENTITY_NAME: 'ENTITY_NAME',
  ENTITY_NUMBER: 'ENTITY_NUMBER',
  COMMENT_START: 'COMMENT_START',
  COMMENT_END: 'COMMENT_END',
  CDATA_START: 'CDATA_START',
  CDATA_END: 'CDATA_END',
  ATTR_NAME: 'ATTR_NAME',
  ATTR_VALUE: 'ATTR_VALUE',
  DOC_TYPE: 'DOC_TYPE',
  EOF: 'EOF'
}
